  # This is a basic workflow to help you get started with Actions
  
  name: build_mainline_linux_kernel
  
  # Controls when the workflow will run
  on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
  
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v4
  
        # Runs a single command using the runners shell
        - name: Run a one-line script
          run: |
            echo Hello, world!


  
        # Runs a set of commands using the runners shell
        - name: Run Download .config script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
            uname -a
            pwd
            neofetch
            wget https://gitlab.postmarketos.org/postmarketOS/pmaports/-/raw/master/device/community/linux-postmarketos-qcom-msm8953/config-postmarketos-qcom-msm8953.aarch64
            cp config-postmarketos-qcom-msm8953.aarch64 .config
            ls -la
            pwd
            cp ${{ github.workspace }}/.config ${{ github.workspace }}/config
            ls -la
            pwd

        - name: Run Download Kernel
          run: |
            #git clone --depth=1 -b 6.15/main https://github.com/msm8953-mainline/linux.git kernel
            pwd
            ls -la
            cp ${{ github.workspace }}/config-postmarketos-qcom-msm8953.aarch64 kernel/.config
            cd kernel
            #make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=aarch64-linux-gnu-gcc -j$(nproc)
            #make -j$(nproc) ARCH=arm64 KBUILD_DEBARCH=arm64 KDEB_CHANGELOG_DIST=mobile CROSS_COMPILE=aarch64-linux-gnu- CC=aarch64-linux-gnu-gcc bindeb-pkg
            #make -j$(nproc) ARCH=arm64 KBUILD_DEBARCH=arm64 KDEB_CHANGELOG_DIST=mobile CROSS_COMPILE=aarch64-linux-gnu- CC=aarch64-linux-gnu-gcc dtbs
            pwd
            ls -la

            
            
        - name: Upload Build file
          uses: actions/upload-artifact@v4
          with:
            name: kernel-config
            path: |
              ${{ github.workspace }}/config-postmarketos-qcom-msm8953.aarch64
              ${{ github.workspace }}/config
              #${{ github.workspace }}/*.deb
              #${{ github.workspace }}/kernel/arm/arm64/boot/*
